### ISSUE TITLE
Optimize MozFest site for mobile

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#135]
driver @edrushka
design: either cassie or Ricardo
design QA: @cassiemc 
dev: @ScottDowne 
signoff: @Saallen 
CC: @simonwex

#### To Do:
- [x] ~~Design mobile comps #131~~
- [x] Implement design QA #132
- [ ] Build 
- [x] Implement ti.to when contract is finalized #130
- [ ] QA build
- [x] Push to prod 
- [ ] Publicize site to email list #129

**Comment by cassiemc** [comment]
@edrushka Do we have a new milestone for this?

**Comment by edrushka** [comment]
@Saallen when do you want to send the email to the list?

**Comment by Saallen** [comment]
@edrushka as soon as we are optimised. I am going to be tied up with Whistler and Scotland for the next two weeks but the email is ready to send so mot much prep needed from me.
How does the next heartbeat sound for folks?

**Comment by Saallen** [comment]
Hey all, do we know where we are with this? Really itchy to start promoting the website and the Call for Proposals? :worried:

**Comment by edrushka** [comment]
From what I understand, @cassiemc has finished her design/review and @ScottDowne has done some (all?) of the coding. The final step is for @jbuck to push the changes live. @jbuck, do you see tickets for this in your queue?

**Comment by jbuck** [comment]
@edrushka I just pushed it to production now, you should see the changes shortly

**Comment by edrushka** [comment]
:bow:

**Comment by thornet** [comment]
Brilliant!

On Wed, Jul 15, 2015 at 5:30 PM, Erika Drushka <notifications@github.com>
wrote:

> [image: :bow:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/2015.mozillafestival.org/issues/135#issuecomment-121653105>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by Saallen** [comment]
:diamonds: :crown:

**Comment by ScottDowne** [comment]
Thinking we can close this. The one ticket left is #129 which I think can probably be closed too?

Either way I'm happy to keep #129 as an independent ticket now.
