### ISSUE TITLE
Master Print and Assembly list

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#315]
@marcwalsh @Saallen perhaps you have a master list somewhere! Thought I'd open this issue to make sure we're not missing anything between @lovegushwa, @natalieworth and I, and others. Please edit this comment to add details as necessary! We can use this for our regroup on Thursday.

## To print at Ravensbourne
(check marks mean the files are complete and ready to go)
- [x] extra hackable posters #301 
- [ ] science fair tags
- [ ] board posters #311 
- [ ] medium sized venue maps
- [ ] photo consent poster #302 
- [ ] emergent session posters
- [ ] 
- [ ] 

## Getting printed elsewhere
(check marks mean the files are complete and ready to be sent to the printer)

- [x] festival guide & posters #212 
- [x] tote bags #225 
- [ ] stickers #209 
- [x] name tags #210 
- [x] t-shirts #208 
- [ ] large venue maps
- [x] space flags with icons #267 
- [ ] session name cards #282

## Needs mounting on foamcore
- [ ] Large maps for wayfinding #279  
- [ ] Board posters #311 
- [ ] Info booth poster #280 

## Needs extra prep-work, like cutting or assembly
- [ ] space flags with icons #267 – need cutting 
- [ ] [Gear store promo card](https://github.com/MozillaFoundation/2015-fundraising/issues/47) – needs stickies and pins attached; need to go into tote bags
- [ ]

**Comment by Saallen** [comment]
@ cassie I dont see the emergent session posters here? Am I missing something?

**Comment by cassiemc** [comment]
@Saallen this isn't a comprehensive list, YET! Please feel free to edit that first comment or leave additions here and I'll update the list. I'm not *totally* clear on what the emergent session posters are... are those a template we previously designed? do you have an issue link?

**Comment by cassiemc** [comment]
This is all tracked much more thoroughly in this doc here: https://docs.google.com/spreadsheets/d/1nOphU77wnjZzkRyAhoo-KiSdZ2nD4HjUg1A4SQykMF4/edit#gid=0
Closing this!
